spring:
    jpa:
        database: H2
        hibernate:
            ddl-auto: validate
            naming:
              physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    datasource:
#        url: jdbc:mysql://192.168.2.46:8306/hgmd
#        url: jdbc:mysql://res-bpci-docker-dev-01.columbuschildrens.net:8306/hgmd
#        url: jdbc:h2:file:./hgmd;INIT=RUNSCRIPT FROM 'classpath:/hgmd-h2.sql'
        url: jdbc:h2:file:./src/main/db/hgmd-h2
        username: sa
        password:
#        driver-class-name: com.mysql.jdbc.Driver
        driver-class-name: org.h2.Driver