spring:
    jpa:
        database: MYSQL
        hibernate:
            ddl-auto: validate

    datasource:
#        url: jdbc:mysql://192.168.2.46:8306/hgmd
#        url: jdbc:mysql://res-bpci-docker-dev-01.columbuschildrens.net:8306/hgmd
        url: jdbc:h2:mem:hgmd;INIT=RUNSCRIPT FROM 'classpath:/hgmd-h2.sql'
        username: root
        password: hgmdp@ss
#        driver-class-name: com.mysql.jdbc.Driver
        driver-class-name: org.h2.Driver